apiVersion: v2
appVersion: latest
description: SearXNG is a free internet metasearch engine which aggregates results from various search services and databases.
name: searxng
version: 2.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - searx
  - searxng
  - search engine
  - privacy
icon: https://github.com/searxng/searxng/blob/master/searx/static/themes/simple/img/favicon.png?raw=true
sources:
  - https://github.com/searxng/searxng
  - https://docs.searxng.org
  - https://hub.docker.com/r/searxng/searxng

maintainers:
  - name: unixfox
    email: searxngatunixfoxdoteu
  - name: Cat Engineer
    email: contact@cat.engineer

dependencies:
  - name: redis
    version: 0.2.2
    repository: https://charts.pascaliske.dev
    condition: searxng.server.limiter
